BrightspaceUI/create

src/generators/default-content/templates/configured/_package.json

Thought about putting this in the `wc-lit-element` template (and I still can), but it complicated matters in that the `npm run lint` script would need to somehow merge it in.

adding lit-analyzer

---

src/generators/default-content/index.js
src/generators/demo/index.js
src/generators/localization/index.js
src/generators/test-unit/index.js
src/generators/test-unit/templates/configured/_element.test.js
src/generators/test-visual-diff/index.js
src/generators/wc-lit-element/index.js

Similar to the move vs. copy problem, I noticed that after running the generator once that the replacements had been made in the source files. This switches things around to do replacements _after_ copying the files.

replacing after copy

---

src/generators/wc-lit-element/templates/configured/_element.js

The existing setup results in a linting error out-of-the-box:
```
29:2 error  Expected constructor to come before static getter localizeConfig  sort-class-members/sort-class-members
```
Just moving the `localizeConfig` bit down under the constructor.

Linting: Move localizeConfig

---

src/generators/demo/templates/_package.json
src/generators/demo/templates/index.html

Now that legacy-Edge is pretty much not something we care about anymore, seems like a good time to stop including the polyfill in our demo pages.

feat: removing web component polyfill from demos

---

src/generators/localization/templates/configured/_element.serge.json

- `es-es`, `fr-fr` and `zh-tw` were being rewritten to themselves
- For political reasons, a base `zh` locale should not be generated from any specific region (other `zh-*` requests should fall back to `en`)

Fix default serge rewrite config

---

.github/workflows/release.yml
README.md
src/generators/release/templates/configured/_README.md
src/generators/release/templates/static/.github/workflows/release.yml
src/generators/test-visual-diff/templates/static/.github/workflows/visual-diff.yml

Our "actions" repo has had its default branch renamed from `master` to `main`. This just updates to point there.

referencing the "actions" repo from its new main branch

---

src/generators/default-content/templates/configured/_package.json

This PR updates the `stylelint` and `@brightspace-ui/stylelint-config` dependencies to support `stylelint@v14`. It also updates the linting script command to lint both HTML and JS files.

Update stylelint and @brightspace-ui/stylelint-config dependencies.

---

src/generators/localization/templates/configured/_element.serge.json

A default `output_lang_rewrite` config has been [implemented](https://github.com/Brightspace/serge-localize/pull/36) and should be relied upon except in special cases.

Remove serge rewrite config

---

src/generators/default-content/templates/configured/_package.json

This is required for eslint >= 7.

adding babel/core dependency

---

.github/dependabot.yml

Until we're ready for Lit 2, we need to tell Dependabot to ignore these major versions. Otherwise when someone uses this to generate a new repo, Dependabot will immediately try to upgrade Lit.

ignoring until Lit 2 upgrade

---

src/generators/default-content/index.js
src/generators/test-unit/templates/configured/_package.json
src/generators/wc-lit-element/templates/configured/_element.js
src/generators/wc-lit-element/templates/configured/_package.json

Upgrading our NPM init library to use Lit 2. I'll make this a major version bump, even though nothing actually depends on it.

Switch to Lit 2

---

src/generators/default-content/templates/configured/_package.json

The change is around `===`, I don't think any other generated code would be affected.

Bump eslint-config-brightspace in generated package.json

---

src/generators/test-unit/templates/configured/_package.json
src/generators/test-unit/templates/static/.github/workflows/ci.yml

We were noticing in CI that without the quotes, only tests inside `test/` would get run, and those inside nested directories would be missed.

fix: escape quotes in wtr calls

---

src/generators/release/templates/static/.github/workflows/release.yml

First, it should be "set up node" not "setup node". But beyond that, the other workflows don't give this step a name and since it's such a standard thing there really isn't any need.

removing "setup node"

---

README.md
src/create.js
src/generators/default-content/index.js
src/generators/default-content/templates/configured/_package.json
src/generators/localization/index.js
src/generators/localization/templates/static/lang/en-gb.js
src/generators/wc-lit-element/index.js
src/generators/wc-lit-element/templates/configured/_element.js

Now that `LocalizationStaticMixin` is gone, this removes it from the `npm init` generator.
I also decided that choosing to enable localization in the first place implied that you wanted Serge support. Seems silly not to.

feat: remove localization type option

---

README.md
src/generators/default-content/templates/configured/_README.md
src/generators/release/templates/configured/_README.md
src/generators/test-unit/templates/configured/_README.md

Mostly this just pairs down the semantic-release blurb since it's all duplicated in the action docs anyway. Also moves the "versioning and releasing" under "Developing and Contributing" since it's only relevant to those folks.

fix: refactor documentation for semantic-release

---

src/generators/demo/templates/index.html

Based on some feedback from @dbatiste in https://github.com/BrightspaceUI/labs/pull/98

fix: wrap demo in <template> and avoid FOUC

---

.github/workflows/release.yml
README.md
src/generators/release/templates/static/.github/workflows/release.yml

Also updated the README with a few things I noticed.
Before merging, I will:
- Delete the old branch protection rule
- Remove `brightspace-bot` as contributor
- Remove access to `D2L_GITHUB_TOKEN`

US158339 - Use new release token

---

src/generators/test-unit/templates/static/.github/workflows/ci.yml

This was missed when this repo was [converted to @brightspace-ui/testing](https://github.com/BrightspaceUI/create/pull/82). Our library automatically installs Playwright.

fix: remove explicit playwright install

---

README.md
package.json
src/create.js
src/generators/demo/index.js
src/generators/test-reporting/index.js
src/generators/test-reporting/templates/configured/_d2l-test-reporting.config.json
src/generators/test-reporting/templates/configured/_gitignore
src/generators/test-unit-axe/index.js
src/generators/test-unit-axe/templates/configured/_d2l-test-reporting.config.json
src/generators/test-unit-axe/templates/configured/_element.axe.js
src/generators/test-unit-axe/templates/configured/_element.test.js
src/generators/test-unit-axe/templates/static/.github/workflows/ci-test-reporting.yml
src/generators/test-vdiff/index.js
src/generators/test-vdiff/templates/configured/_d2l-test-reporting.config.json
src/generators/test-vdiff/templates/static/.github/workflows/vdiff-test-reporting.yml
src/generators/wc-lit-element/index.js
src/helper.js

https://desire2learn.atlassian.net/browse/QE-264
This adds the configuration pieces for test reporting and fixes a few other minor inconsistencies.

feat: add test reporting to component generation

---

src/generators/test-unit-axe/index.js

Looks like this eslint config file for tests got [lost as part of this change](https://github.com/BrightspaceUI/create/pull/94/files#diff-96f7715979e48903f3108fbdce371af4251b8689343c3f675113751c18fba5d4L21).

fix: restore eslint for tests
